# Generated by Django 4.1 on 2022-08-28 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tutorialcategory_tutorial_tutorial_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 11, 36, 4, 55228), verbose_name='date published'),
        ),
    ]
