# Generated by Django 4.1 on 2022-08-29 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_tutorial_tutorial_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='tutorial_category',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.tutorialseries', verbose_name='Series'),
        ),
    ]
